### ISSUE TITLE
[request] aggiunta dei tracker standard di TNTVillage nel magnet

### ISSUE THREAD

**Issue by zeroone2numeral2** [TNTBack/tntback.github.io#1]
Ciao,

Volevo suggerire di includere nel link magnet anche i [tracker standard](https://github.com/zeroone2numeral2/tnt-village-bot/blob/f1246bf97bca369ce0a196a75ef763da74c44c17/bot/handlers/magnet_with_trackers.py#L21) che erano presenti in ogni release di TNTVillage. Sono ancora up, quindi dovrebbero rendere il download un po' più veloce

**Comment by TNTBack** [comment]
Grazie mille per il suggerimento
Risolto col commit: f33172f2f895a9ab0466403ca7257d6369bea864
